### ISSUE TITLE
what is even this?

### ISSUE THREAD

**Issue by ferxsy** [jlop007/apple-replica-starter-files#2]
you placing fucking files with just a "Apple" Title? delete this lamo

**Comment by jlop007** [comment]
Learn how to read. The repo clearly states "starter files", not "completed code". These "starter files" are meant for people that want to follow my tutorial on YouTube.

**Comment by ferxsy** [comment]
> Learn how to read. The repo clearly states "starter files", not "completed code". These "starter files" are meant for people that want to follow my tutorial on YouTube.

I dont think someone is that stupid to dont know how to Link/Place new files on their editor, anyways, thanks.

**Comment by jlop007** [comment]
It has nothing to do with people's abilities. The main purpose of the repo is to save people time by providing a boilerplate with all the related assets, especially things like images/videos/fonts; this is very common in the tutorial space.
